---
- include: vlc/vlc.yaml
- include: transmission/transmission.yaml
- include: appcleaner/appcleaner.yaml
- include: keka/keka.yaml
- include: limechat/limechat.yaml
- include: firefox/firefox.yaml
# - include: opera/opera.yaml
- include: mou/mou.yaml
- include: texts/texts.yaml