---
- hosts: self
  user: jgeerling
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew

  tasks:
    - name: Ensure Ansible downloads directory exists.
      file:
        path: "{{ downloads }}"
        state: directory

    - include: tasks/dotfiles.yml
    - include: tasks/preferences.yml
