---
- hosts: localhost
  user: jgeerling
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew

  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/dotfiles.yml
    - include: tasks/preferences.yml
