---
- include: ../setup.yaml

- hosts: $hosts
  user: $user
  vars:
    install_type: app
    app_name: VLC
    app_name_pretty: VLC
    app_url: https://copy.com/8WKZ3x1ZWOIC/VLC-2.0.6.dmg?download=1
    mount_path: /Volumes/vlc-2.0.6/
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../install-type/dmg.yaml