---
- include: ../local-setup.yaml

- hosts: $hosts
  user: $user
  gather_facts: false
  vars:
    install_type: pkg
    install_target: /Volumes/OSX
    app_name: Vagrant
    app_name_pretty: Vagrant
    app_url: http://files.vagrantup.com/packages/64e360814c3ad960d810456add977fd4c7d47ce6/Vagrant.dmg
    mount_path: /Volumes/Vagrant/
  vars_files:
    - ../local-setup-vars.yaml
  tasks:
    - include: ../file/dmg.pkg