---
- include: ../local-setup.yaml

- hosts: $hosts
  user: $user
  gather_facts: false
  vars:
    install_type: app
    app_name: SourceTree
    app_name_pretty: SourceTree
    app_url: https://copy.com/RDxUBW9uhWiQ/SourceTree-1.5.8.dmg?download=1
    mount_path: /Volumes/SourceTree/
  vars_files:
    - ../local-setup-vars.yaml
  tasks:
    - include: ../file/dmg.yaml