---
- include: ../setup.yaml

- hosts: $hosts
  user: $user
  vars:
    install_type: app
    app_name: iTerm
    app_name_pretty: iTerm
    app_url: https://copy.com/HTIIPAwoiKVY
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../install-type/zip.yaml