---
- include: ../setup.yaml

- hosts: $hosts
  user: $user
  vars:
    install_type: app
    app_name: Transmission
    app_name_pretty: Transmission
    app_url: https://copy.com/jTqaA0JWmTmn/Transmission-2.77.dmg?download=1
    mount_path: /Volumes/Transmission/
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../install-type/dmg.yaml