---
- include: ../local-setup.yaml

- hosts: $hosts
  user: $user
  gather_facts: false
  vars:
    install_type: pkg
    install_target: /Volumes/OSX
    app_name: VirtualBox
    app_name_pretty: VirtualBox
    app_url: http://download.virtualbox.org/virtualbox/4.2.12/VirtualBox-4.2.12-84980-OSX.dmg
    mount_path: /Volumes/VirtualBox/
  vars_files:
    - ../local-setup-vars.yaml
  tasks:
    - include: ../file/dmg.yaml